### ISSUE TITLE
I have a compile problem

### ISSUE THREAD

**Issue by yuqitian** [trymbill/cordova.parse.ios.deviceToken#1]
The following build commands failed:
1>  	Check dependencies
1>  (1 failure)
1>  Failed to build app for buildNumber 617: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/cordova/build-release.xcconfig,-project,XXXX.xcodeproj,ARCHS=armv7 arm64,-target,X'X'X,-configuration,Release,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/build/sharedpch
1>MSBUILD : cordova-build error : Error: 生成服务器 生成失败，错误 Error code 65 for command: xcodebuild with args: -xcconfig,/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/cordova/build-release.xcconfig,-project,XXXX.xcodeproj,ARCHS=armv7 arm64,-target,XXXX,-configuration,Release,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/tianyuqi/.taco_home/remote-builds/taco-remote/builds/617/cordovaApp/platforms/ios/build/sharedpch 中的远程生成错误 - 1

**Comment by trymbill** [comment]
Hey @yuqitian, this repository isn't under active development and since I don't use Parse anymore I can't really help you with your problem. Sorry about that!
